# Redis Password
requirepass redisa1a1a1

# Bind to all interfaces (adjust if you want local only)
bind 0.0.0.0

# Security
protected-mode yes

# Persistence
save 900 1
save 300 10
save 60 10000
dir /data
appendonly yes